name: "Ian Martins"
description: "Este é meu blog pessoal. Aqui estarei compartilhando o que achar necessário lembrar e praticar"
url: "http://ianmartins.github.io/"
paginate: 5
markdown: kramdown
permalink: pretty
github: https://github.com/ianmartins/ianmartins.github.io
analytics:
  provider: google
google:
  tracking_id: 'UA-61213000-1'
